title: "Développeur web fullstack à Bordeaux"
email: your-email@example.com
version: 1-0-4
description: >- # this means to ignore newlines until "baseurl:"
  "Passionné, curieux et créatif, je conçois des solutions digitales, maquette et développe des sites - Arthaud Proust"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
seo: 
  author: "Arthaud Proust"
  url: "https://arthaudproust.fr"
  title: "Développeur web fullstack à Bordeaux"
  desc: "Passionné, curieux et créatif, je conçois des solutions digitales, maquette et développe des sites - Arthaud Proust"
  links: 
    - https://github.com/arthaud-proust
    - https://www.linkedin.com/in/arthaud-proust/
    - https://twitter.com/arthaud_proust
    - https://www.facebook.com/arthaudproust.fr
    - https://www.instagram.com/arthauproust/

exclude:
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.mix.js
  - workspace.code-workspace

collections:
  realisations:
    output: true
    permalink: /:collection/:name/

sass:
  style: compact # possible values: nested expanded compact compressed