title: "Développeur web fullstack à Bordeaux"
email: contact@arthaudproust.fr
phone: "07 83 39 28 88"
description: >- # this means to ignore newlines until "baseurl:"
  "Passionné, curieux et créatif, je conçois des solutions digitales, maquette et développe des sites - Arthaud Proust"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
seo: 
  author: "Arthaud Proust"
  url: "https://arthaudproust.fr"
  title: "Développeur web fullstack à Bordeaux"
  desc: "Passionné, curieux et créatif, je conçois des solutions digitales, maquette et développe des sites - Arthaud Proust"
  links: 
    github: https://github.com/arthaud-proust
    linkedin: https://www.linkedin.com/in/arthaud-proust/
    twitter: https://twitter.com/arthaud_proust
    facebook: https://www.facebook.com/arthaudproust.fr
    instagram: https://www.instagram.com/arthauproust/

exclude:
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.mix.js
  - workspace.code-workspace

imgFolder:
  realisations: /assets/realisations/
  galleries: /assets/galleries/


collections:
  realisations:
    output: true
    permalink: /:collection/:name/
  galleries:
    output: true
    permalink: /:collection/:name/
sass:
  style: compressed # possible values: nested expanded compact compressed